package services

// StaticHolding represents a single holding in an ETF
type StaticHolding struct {
	Symbol string
	Name   string
	Weight float64 // percentage, e.g. 5.2 = 5.2%
	Sector string
}

// staticHoldings contains manually maintained top holdings for core ETFs.
// Data sourced from public ETF fact sheets and holdings disclosures.
var staticHoldings = map[string][]StaticHolding{
	"SCHD": {
		{Symbol: "AVGO", Name: "Broadcom Inc", Weight: 5.82, Sector: "Technology"},
		{Symbol: "ABBV", Name: "AbbVie Inc", Weight: 5.15, Sector: "Healthcare"},
		{Symbol: "JPM", Name: "JPMorgan Chase & Co", Weight: 4.68, Sector: "Financials"},
		{Symbol: "MRK", Name: "Merck & Co Inc", Weight: 4.31, Sector: "Healthcare"},
		{Symbol: "PEP", Name: "PepsiCo Inc", Weight: 4.12, Sector: "Consumer Staples"},
		{Symbol: "TXN", Name: "Texas Instruments", Weight: 3.95, Sector: "Technology"},
		{Symbol: "HD", Name: "Home Depot Inc", Weight: 3.74, Sector: "Consumer Discretionary"},
		{Symbol: "CSCO", Name: "Cisco Systems Inc", Weight: 3.52, Sector: "Technology"},
		{Symbol: "VZ", Name: "Verizon Communications", Weight: 3.38, Sector: "Communication Services"},
		{Symbol: "KO", Name: "Coca-Cola Co", Weight: 3.21, Sector: "Consumer Staples"},
		{Symbol: "CVX", Name: "Chevron Corp", Weight: 3.05, Sector: "Energy"},
		{Symbol: "AMGN", Name: "Amgen Inc", Weight: 2.91, Sector: "Healthcare"},
		{Symbol: "PG", Name: "Procter & Gamble Co", Weight: 2.78, Sector: "Consumer Staples"},
		{Symbol: "MCD", Name: "McDonald's Corp", Weight: 2.65, Sector: "Consumer Discretionary"},
		{Symbol: "IBM", Name: "IBM Corp", Weight: 2.51, Sector: "Technology"},
		{Symbol: "UNH", Name: "UnitedHealth Group", Weight: 2.38, Sector: "Healthcare"},
		{Symbol: "SCHW", Name: "Charles Schwab Corp", Weight: 2.24, Sector: "Financials"},
		{Symbol: "BLK", Name: "BlackRock Inc", Weight: 2.11, Sector: "Financials"},
		{Symbol: "LOW", Name: "Lowe's Companies", Weight: 1.98, Sector: "Consumer Discretionary"},
		{Symbol: "PFE", Name: "Pfizer Inc", Weight: 1.85, Sector: "Healthcare"},
	},
	"JEPI": {
		{Symbol: "ROST", Name: "Ross Stores Inc", Weight: 2.38, Sector: "Consumer Discretionary"},
		{Symbol: "NVDA", Name: "NVIDIA Corp", Weight: 2.21, Sector: "Technology"},
		{Symbol: "AAPL", Name: "Apple Inc", Weight: 2.15, Sector: "Technology"},
		{Symbol: "ETN", Name: "Eaton Corp", Weight: 2.08, Sector: "Industrials"},
		{Symbol: "MSFT", Name: "Microsoft Corp", Weight: 1.95, Sector: "Technology"},
		{Symbol: "META", Name: "Meta Platforms Inc", Weight: 1.87, Sector: "Communication Services"},
		{Symbol: "V", Name: "Visa Inc", Weight: 1.79, Sector: "Financials"},
		{Symbol: "UNH", Name: "UnitedHealth Group", Weight: 1.72, Sector: "Healthcare"},
		{Symbol: "AMZN", Name: "Amazon.com Inc", Weight: 1.65, Sector: "Consumer Discretionary"},
		{Symbol: "GOOGL", Name: "Alphabet Inc", Weight: 1.58, Sector: "Communication Services"},
		{Symbol: "MA", Name: "Mastercard Inc", Weight: 1.51, Sector: "Financials"},
		{Symbol: "COST", Name: "Costco Wholesale", Weight: 1.44, Sector: "Consumer Staples"},
		{Symbol: "LLY", Name: "Eli Lilly & Co", Weight: 1.37, Sector: "Healthcare"},
		{Symbol: "ABBV", Name: "AbbVie Inc", Weight: 1.31, Sector: "Healthcare"},
		{Symbol: "HD", Name: "Home Depot Inc", Weight: 1.24, Sector: "Consumer Discretionary"},
		{Symbol: "MRK", Name: "Merck & Co Inc", Weight: 1.18, Sector: "Healthcare"},
		{Symbol: "PEP", Name: "PepsiCo Inc", Weight: 1.12, Sector: "Consumer Staples"},
		{Symbol: "TMO", Name: "Thermo Fisher Scientific", Weight: 1.06, Sector: "Healthcare"},
		{Symbol: "CSCO", Name: "Cisco Systems Inc", Weight: 1.01, Sector: "Technology"},
		{Symbol: "WMT", Name: "Walmart Inc", Weight: 0.95, Sector: "Consumer Staples"},
	},
	"JEPQ": {
		{Symbol: "NVDA", Name: "NVIDIA Corp", Weight: 7.43, Sector: "Technology"},
		{Symbol: "AAPL", Name: "Apple Inc", Weight: 6.30, Sector: "Technology"},
		{Symbol: "GOOGL", Name: "Alphabet Inc", Weight: 5.30, Sector: "Communication Services"},
		{Symbol: "MU", Name: "Micron Technology", Weight: 4.86, Sector: "Technology"},
		{Symbol: "MSFT", Name: "Microsoft Corp", Weight: 4.50, Sector: "Technology"},
		{Symbol: "AMZN", Name: "Amazon.com Inc", Weight: 4.21, Sector: "Consumer Discretionary"},
		{Symbol: "META", Name: "Meta Platforms Inc", Weight: 3.95, Sector: "Communication Services"},
		{Symbol: "NFLX", Name: "Netflix Inc", Weight: 3.68, Sector: "Communication Services"},
		{Symbol: "AVGO", Name: "Broadcom Inc", Weight: 3.42, Sector: "Technology"},
		{Symbol: "AMD", Name: "Advanced Micro Devices", Weight: 3.15, Sector: "Technology"},
		{Symbol: "COST", Name: "Costco Wholesale", Weight: 2.88, Sector: "Consumer Staples"},
		{Symbol: "LLY", Name: "Eli Lilly & Co", Weight: 2.61, Sector: "Healthcare"},
		{Symbol: "CRM", Name: "Salesforce Inc", Weight: 2.34, Sector: "Technology"},
		{Symbol: "ADBE", Name: "Adobe Inc", Weight: 2.07, Sector: "Technology"},
		{Symbol: "INTC", Name: "Intel Corp", Weight: 1.82, Sector: "Technology"},
		{Symbol: "CSCO", Name: "Cisco Systems Inc", Weight: 1.58, Sector: "Technology"},
		{Symbol: "QCOM", Name: "Qualcomm Inc", Weight: 1.35, Sector: "Technology"},
		{Symbol: "TXN", Name: "Texas Instruments", Weight: 1.12, Sector: "Technology"},
		{Symbol: "AMAT", Name: "Applied Materials", Weight: 0.95, Sector: "Technology"},
		{Symbol: "ISRG", Name: "Intuitive Surgical", Weight: 0.78, Sector: "Healthcare"},
	},
	"QQQ": {
		{Symbol: "MSFT", Name: "Microsoft Corp", Weight: 8.92, Sector: "Technology"},
		{Symbol: "AAPL", Name: "Apple Inc", Weight: 8.15, Sector: "Technology"},
		{Symbol: "NVDA", Name: "NVIDIA Corp", Weight: 7.38, Sector: "Technology"},
		{Symbol: "AMZN", Name: "Amazon.com Inc", Weight: 6.21, Sector: "Consumer Discretionary"},
		{Symbol: "META", Name: "Meta Platforms Inc", Weight: 4.85, Sector: "Communication Services"},
		{Symbol: "GOOGL", Name: "Alphabet Inc Class A", Weight: 4.12, Sector: "Communication Services"},
		{Symbol: "GOOG", Name: "Alphabet Inc Class C", Weight: 3.98, Sector: "Communication Services"},
		{Symbol: "AVGO", Name: "Broadcom Inc", Weight: 3.45, Sector: "Technology"},
		{Symbol: "TSLA", Name: "Tesla Inc", Weight: 3.12, Sector: "Consumer Discretionary"},
		{Symbol: "COST", Name: "Costco Wholesale", Weight: 2.58, Sector: "Consumer Staples"},
		{Symbol: "NFLX", Name: "Netflix Inc", Weight: 2.31, Sector: "Communication Services"},
		{Symbol: "AMD", Name: "Advanced Micro Devices", Weight: 2.08, Sector: "Technology"},
		{Symbol: "ADBE", Name: "Adobe Inc", Weight: 1.85, Sector: "Technology"},
		{Symbol: "PEP", Name: "PepsiCo Inc", Weight: 1.62, Sector: "Consumer Staples"},
		{Symbol: "LIN", Name: "Linde plc", Weight: 1.48, Sector: "Materials"},
		{Symbol: "CSCO", Name: "Cisco Systems Inc", Weight: 1.35, Sector: "Technology"},
		{Symbol: "INTC", Name: "Intel Corp", Weight: 1.22, Sector: "Technology"},
		{Symbol: "CMCSA", Name: "Comcast Corp", Weight: 1.08, Sector: "Communication Services"},
		{Symbol: "QCOM", Name: "Qualcomm Inc", Weight: 0.95, Sector: "Technology"},
		{Symbol: "TXN", Name: "Texas Instruments", Weight: 0.82, Sector: "Technology"},
		{Symbol: "AMGN", Name: "Amgen Inc", Weight: 0.75, Sector: "Healthcare"},
		{Symbol: "HON", Name: "Honeywell International", Weight: 0.68, Sector: "Industrials"},
		{Symbol: "SBUX", Name: "Starbucks Corp", Weight: 0.55, Sector: "Consumer Discretionary"},
		{Symbol: "GILD", Name: "Gilead Sciences", Weight: 0.48, Sector: "Healthcare"},
		{Symbol: "BKNG", Name: "Booking Holdings", Weight: 0.42, Sector: "Consumer Discretionary"},
	},
	"VTI": {
		{Symbol: "AAPL", Name: "Apple Inc", Weight: 6.12, Sector: "Technology"},
		{Symbol: "MSFT", Name: "Microsoft Corp", Weight: 5.85, Sector: "Technology"},
		{Symbol: "NVDA", Name: "NVIDIA Corp", Weight: 4.92, Sector: "Technology"},
		{Symbol: "AMZN", Name: "Amazon.com Inc", Weight: 3.45, Sector: "Consumer Discretionary"},
		{Symbol: "META", Name: "Meta Platforms Inc", Weight: 2.68, Sector: "Communication Services"},
		{Symbol: "GOOGL", Name: "Alphabet Inc", Weight: 2.35, Sector: "Communication Services"},
		{Symbol: "GOOG", Name: "Alphabet Inc Class C", Weight: 2.21, Sector: "Communication Services"},
		{Symbol: "BRK.B", Name: "Berkshire Hathaway", Weight: 1.95, Sector: "Financials"},
		{Symbol: "AVGO", Name: "Broadcom Inc", Weight: 1.78, Sector: "Technology"},
		{Symbol: "TSLA", Name: "Tesla Inc", Weight: 1.62, Sector: "Consumer Discretionary"},
		{Symbol: "LLY", Name: "Eli Lilly & Co", Weight: 1.45, Sector: "Healthcare"},
		{Symbol: "JPM", Name: "JPMorgan Chase & Co", Weight: 1.32, Sector: "Financials"},
		{Symbol: "V", Name: "Visa Inc", Weight: 1.18, Sector: "Financials"},
		{Symbol: "UNH", Name: "UnitedHealth Group", Weight: 1.05, Sector: "Healthcare"},
		{Symbol: "XOM", Name: "Exxon Mobil Corp", Weight: 0.95, Sector: "Energy"},
		{Symbol: "MA", Name: "Mastercard Inc", Weight: 0.88, Sector: "Financials"},
		{Symbol: "JNJ", Name: "Johnson & Johnson", Weight: 0.82, Sector: "Healthcare"},
		{Symbol: "PG", Name: "Procter & Gamble Co", Weight: 0.75, Sector: "Consumer Staples"},
		{Symbol: "HD", Name: "Home Depot Inc", Weight: 0.68, Sector: "Consumer Discretionary"},
		{Symbol: "COST", Name: "Costco Wholesale", Weight: 0.62, Sector: "Consumer Staples"},
		{Symbol: "ABBV", Name: "AbbVie Inc", Weight: 0.58, Sector: "Healthcare"},
		{Symbol: "MRK", Name: "Merck & Co Inc", Weight: 0.52, Sector: "Healthcare"},
		{Symbol: "PEP", Name: "PepsiCo Inc", Weight: 0.48, Sector: "Consumer Staples"},
		{Symbol: "KO", Name: "Coca-Cola Co", Weight: 0.45, Sector: "Consumer Staples"},
		{Symbol: "CVX", Name: "Chevron Corp", Weight: 0.42, Sector: "Energy"},
	},
	"SPY": {
		{Symbol: "AAPL", Name: "Apple Inc", Weight: 7.15, Sector: "Technology"},
		{Symbol: "MSFT", Name: "Microsoft Corp", Weight: 6.82, Sector: "Technology"},
		{Symbol: "NVDA", Name: "NVIDIA Corp", Weight: 5.68, Sector: "Technology"},
		{Symbol: "AMZN", Name: "Amazon.com Inc", Weight: 3.92, Sector: "Consumer Discretionary"},
		{Symbol: "META", Name: "Meta Platforms Inc", Weight: 3.15, Sector: "Communication Services"},
		{Symbol: "GOOGL", Name: "Alphabet Inc", Weight: 2.78, Sector: "Communication Services"},
		{Symbol: "GOOG", Name: "Alphabet Inc Class C", Weight: 2.62, Sector: "Communication Services"},
		{Symbol: "BRK.B", Name: "Berkshire Hathaway", Weight: 2.25, Sector: "Financials"},
		{Symbol: "AVGO", Name: "Broadcom Inc", Weight: 2.08, Sector: "Technology"},
		{Symbol: "TSLA", Name: "Tesla Inc", Weight: 1.85, Sector: "Consumer Discretionary"},
		{Symbol: "LLY", Name: "Eli Lilly & Co", Weight: 1.68, Sector: "Healthcare"},
		{Symbol: "JPM", Name: "JPMorgan Chase & Co", Weight: 1.52, Sector: "Financials"},
		{Symbol: "V", Name: "Visa Inc", Weight: 1.35, Sector: "Financials"},
		{Symbol: "UNH", Name: "UnitedHealth Group", Weight: 1.22, Sector: "Healthcare"},
		{Symbol: "XOM", Name: "Exxon Mobil Corp", Weight: 1.08, Sector: "Energy"},
		{Symbol: "MA", Name: "Mastercard Inc", Weight: 0.98, Sector: "Financials"},
		{Symbol: "JNJ", Name: "Johnson & Johnson", Weight: 0.88, Sector: "Healthcare"},
		{Symbol: "PG", Name: "Procter & Gamble Co", Weight: 0.78, Sector: "Consumer Staples"},
		{Symbol: "HD", Name: "Home Depot Inc", Weight: 0.72, Sector: "Consumer Discretionary"},
		{Symbol: "COST", Name: "Costco Wholesale", Weight: 0.65, Sector: "Consumer Staples"},
	},
	"VYM": {
		{Symbol: "JPM", Name: "JPMorgan Chase & Co", Weight: 4.52, Sector: "Financials"},
		{Symbol: "JNJ", Name: "Johnson & Johnson", Weight: 3.85, Sector: "Healthcare"},
		{Symbol: "XOM", Name: "Exxon Mobil Corp", Weight: 3.62, Sector: "Energy"},
		{Symbol: "PG", Name: "Procter & Gamble Co", Weight: 3.38, Sector: "Consumer Staples"},
		{Symbol: "CVX", Name: "Chevron Corp", Weight: 3.15, Sector: "Energy"},
		{Symbol: "HD", Name: "Home Depot Inc", Weight: 2.92, Sector: "Consumer Discretionary"},
		{Symbol: "KO", Name: "Coca-Cola Co", Weight: 2.75, Sector: "Consumer Staples"},
		{Symbol: "MRK", Name: "Merck & Co Inc", Weight: 2.58, Sector: "Healthcare"},
		{Symbol: "ABBV", Name: "AbbVie Inc", Weight: 2.42, Sector: "Healthcare"},
		{Symbol: "PEP", Name: "PepsiCo Inc", Weight: 2.25, Sector: "Consumer Staples"},
		{Symbol: "VZ", Name: "Verizon Communications", Weight: 2.08, Sector: "Communication Services"},
		{Symbol: "AVGO", Name: "Broadcom Inc", Weight: 1.95, Sector: "Technology"},
		{Symbol: "CSCO", Name: "Cisco Systems Inc", Weight: 1.82, Sector: "Technology"},
		{Symbol: "MCD", Name: "McDonald's Corp", Weight: 1.68, Sector: "Consumer Discretionary"},
		{Symbol: "IBM", Name: "IBM Corp", Weight: 1.55, Sector: "Technology"},
		{Symbol: "TXN", Name: "Texas Instruments", Weight: 1.42, Sector: "Technology"},
		{Symbol: "WMT", Name: "Walmart Inc", Weight: 1.35, Sector: "Consumer Staples"},
		{Symbol: "UNP", Name: "Union Pacific Corp", Weight: 1.22, Sector: "Industrials"},
		{Symbol: "LOW", Name: "Lowe's Companies", Weight: 1.08, Sector: "Consumer Discretionary"},
		{Symbol: "AMGN", Name: "Amgen Inc", Weight: 0.95, Sector: "Healthcare"},
	},
	"SPYD": {
		{Symbol: "VZ", Name: "Verizon Communications", Weight: 2.85, Sector: "Communication Services"},
		{Symbol: "MO", Name: "Altria Group", Weight: 2.62, Sector: "Consumer Staples"},
		{Symbol: "T", Name: "AT&T Inc", Weight: 2.45, Sector: "Communication Services"},
		{Symbol: "XOM", Name: "Exxon Mobil Corp", Weight: 2.32, Sector: "Energy"},
		{Symbol: "CVX", Name: "Chevron Corp", Weight: 2.18, Sector: "Energy"},
		{Symbol: "IBM", Name: "IBM Corp", Weight: 2.05, Sector: "Technology"},
		{Symbol: "KO", Name: "Coca-Cola Co", Weight: 1.92, Sector: "Consumer Staples"},
		{Symbol: "PFE", Name: "Pfizer Inc", Weight: 1.78, Sector: "Healthcare"},
		{Symbol: "JNJ", Name: "Johnson & Johnson", Weight: 1.65, Sector: "Healthcare"},
		{Symbol: "PG", Name: "Procter & Gamble Co", Weight: 1.52, Sector: "Consumer Staples"},
		{Symbol: "DOW", Name: "Dow Inc", Weight: 1.45, Sector: "Materials"},
		{Symbol: "VFC", Name: "VF Corp", Weight: 1.38, Sector: "Consumer Discretionary"},
		{Symbol: "WBA", Name: "Walgreens Boots Alliance", Weight: 1.25, Sector: "Healthcare"},
		{Symbol: "CSCO", Name: "Cisco Systems Inc", Weight: 1.18, Sector: "Technology"},
		{Symbol: "SOLV", Name: "Solventum Corp", Weight: 1.05, Sector: "Healthcare"},
		{Symbol: "GIS", Name: "General Mills", Weight: 0.98, Sector: "Consumer Staples"},
		{Symbol: "MMM", Name: "3M Co", Weight: 0.92, Sector: "Industrials"},
		{Symbol: "LYB", Name: "LyondellBasell", Weight: 0.85, Sector: "Materials"},
		{Symbol: "NEM", Name: "Newmont Corp", Weight: 0.78, Sector: "Materials"},
		{Symbol: "WMB", Name: "Williams Companies", Weight: 0.72, Sector: "Energy"},
	},
	"HDV": {
		{Symbol: "XOM", Name: "Exxon Mobil Corp", Weight: 9.85, Sector: "Energy"},
		{Symbol: "CVX", Name: "Chevron Corp", Weight: 7.42, Sector: "Energy"},
		{Symbol: "ABBV", Name: "AbbVie Inc", Weight: 6.15, Sector: "Healthcare"},
		{Symbol: "JNJ", Name: "Johnson & Johnson", Weight: 5.82, Sector: "Healthcare"},
		{Symbol: "PEP", Name: "PepsiCo Inc", Weight: 5.35, Sector: "Consumer Staples"},
		{Symbol: "KO", Name: "Coca-Cola Co", Weight: 4.98, Sector: "Consumer Staples"},
		{Symbol: "MRK", Name: "Merck & Co Inc", Weight: 4.62, Sector: "Healthcare"},
		{Symbol: "PG", Name: "Procter & Gamble Co", Weight: 4.25, Sector: "Consumer Staples"},
		{Symbol: "VZ", Name: "Verizon Communications", Weight: 3.88, Sector: "Communication Services"},
		{Symbol: "MCD", Name: "McDonald's Corp", Weight: 3.52, Sector: "Consumer Discretionary"},
		{Symbol: "CSCO", Name: "Cisco Systems Inc", Weight: 3.15, Sector: "Technology"},
		{Symbol: "IBM", Name: "IBM Corp", Weight: 2.82, Sector: "Technology"},
		{Symbol: "AMGN", Name: "Amgen Inc", Weight: 2.55, Sector: "Healthcare"},
		{Symbol: "UNP", Name: "Union Pacific Corp", Weight: 2.28, Sector: "Industrials"},
		{Symbol: "T", Name: "AT&T Inc", Weight: 2.05, Sector: "Communication Services"},
		{Symbol: "TXN", Name: "Texas Instruments", Weight: 1.82, Sector: "Technology"},
		{Symbol: "MO", Name: "Altria Group", Weight: 1.65, Sector: "Consumer Staples"},
		{Symbol: "LOW", Name: "Lowe's Companies", Weight: 1.48, Sector: "Consumer Discretionary"},
		{Symbol: "NEE", Name: "NextEra Energy", Weight: 1.32, Sector: "Utilities"},
		{Symbol: "OKE", Name: "ONEOK Inc", Weight: 1.15, Sector: "Energy"},
	},
	"DGRO": {
		{Symbol: "AVGO", Name: "Broadcom Inc", Weight: 4.52, Sector: "Technology"},
		{Symbol: "JPM", Name: "JPMorgan Chase & Co", Weight: 4.18, Sector: "Financials"},
		{Symbol: "MSFT", Name: "Microsoft Corp", Weight: 3.85, Sector: "Technology"},
		{Symbol: "AAPL", Name: "Apple Inc", Weight: 3.52, Sector: "Technology"},
		{Symbol: "ABBV", Name: "AbbVie Inc", Weight: 3.25, Sector: "Healthcare"},
		{Symbol: "UNH", Name: "UnitedHealth Group", Weight: 2.98, Sector: "Healthcare"},
		{Symbol: "V", Name: "Visa Inc", Weight: 2.72, Sector: "Financials"},
		{Symbol: "HD", Name: "Home Depot Inc", Weight: 2.45, Sector: "Consumer Discretionary"},
		{Symbol: "PG", Name: "Procter & Gamble Co", Weight: 2.18, Sector: "Consumer Staples"},
		{Symbol: "MRK", Name: "Merck & Co Inc", Weight: 1.95, Sector: "Healthcare"},
		{Symbol: "COST", Name: "Costco Wholesale", Weight: 1.78, Sector: "Consumer Staples"},
		{Symbol: "PEP", Name: "PepsiCo Inc", Weight: 1.62, Sector: "Consumer Staples"},
		{Symbol: "KO", Name: "Coca-Cola Co", Weight: 1.48, Sector: "Consumer Staples"},
		{Symbol: "TXN", Name: "Texas Instruments", Weight: 1.35, Sector: "Technology"},
		{Symbol: "AMGN", Name: "Amgen Inc", Weight: 1.22, Sector: "Healthcare"},
		{Symbol: "MCD", Name: "McDonald's Corp", Weight: 1.08, Sector: "Consumer Discretionary"},
		{Symbol: "CSCO", Name: "Cisco Systems Inc", Weight: 0.95, Sector: "Technology"},
		{Symbol: "BLK", Name: "BlackRock Inc", Weight: 0.82, Sector: "Financials"},
		{Symbol: "SCHW", Name: "Charles Schwab Corp", Weight: 0.75, Sector: "Financials"},
		{Symbol: "LOW", Name: "Lowe's Companies", Weight: 0.68, Sector: "Consumer Discretionary"},
	},
	"VNQ": {
		{Symbol: "PLD", Name: "Prologis Inc", Weight: 7.85, Sector: "Real Estate"},
		{Symbol: "AMT", Name: "American Tower Corp", Weight: 6.42, Sector: "Real Estate"},
		{Symbol: "EQIX", Name: "Equinix Inc", Weight: 5.18, Sector: "Real Estate"},
		{Symbol: "DLR", Name: "Digital Realty Trust", Weight: 4.52, Sector: "Real Estate"},
		{Symbol: "SPG", Name: "Simon Property Group", Weight: 3.85, Sector: "Real Estate"},
		{Symbol: "O", Name: "Realty Income Corp", Weight: 3.42, Sector: "Real Estate"},
		{Symbol: "WELL", Name: "Welltower Inc", Weight: 3.15, Sector: "Real Estate"},
		{Symbol: "PSA", Name: "Public Storage", Weight: 2.88, Sector: "Real Estate"},
		{Symbol: "CCI", Name: "Crown Castle Inc", Weight: 2.62, Sector: "Real Estate"},
		{Symbol: "AVB", Name: "AvalonBay Communities", Weight: 2.35, Sector: "Real Estate"},
		{Symbol: "EQR", Name: "Equity Residential", Weight: 2.08, Sector: "Real Estate"},
		{Symbol: "WY", Name: "Weyerhaeuser Co", Weight: 1.85, Sector: "Real Estate"},
		{Symbol: "VICI", Name: "VICI Properties", Weight: 1.68, Sector: "Real Estate"},
		{Symbol: "ARE", Name: "Alexandria Real Estate", Weight: 1.52, Sector: "Real Estate"},
		{Symbol: "MAA", Name: "Mid-America Apartment", Weight: 1.35, Sector: "Real Estate"},
		{Symbol: "UDR", Name: "UDR Inc", Weight: 1.18, Sector: "Real Estate"},
		{Symbol: "ESS", Name: "Essex Property Trust", Weight: 1.05, Sector: "Real Estate"},
		{Symbol: "PEAK", Name: "Healthpeak Properties", Weight: 0.92, Sector: "Real Estate"},
		{Symbol: "KIM", Name: "Kimco Realty", Weight: 0.78, Sector: "Real Estate"},
		{Symbol: "REG", Name: "Regency Centers", Weight: 0.65, Sector: "Real Estate"},
	},
	"BND": {
		{Symbol: "UST2Y", Name: "US Treasury 2Y", Weight: 8.52, Sector: "Government"},
		{Symbol: "UST5Y", Name: "US Treasury 5Y", Weight: 7.85, Sector: "Government"},
		{Symbol: "UST10Y", Name: "US Treasury 10Y", Weight: 6.42, Sector: "Government"},
		{Symbol: "UST30Y", Name: "US Treasury 30Y", Weight: 5.18, Sector: "Government"},
		{Symbol: "GNMA", Name: "GNMA MBS", Weight: 4.52, Sector: "Government"},
		{Symbol: "FNMA", Name: "FNMA MBS", Weight: 3.85, Sector: "Government"},
		{Symbol: "FHLMC", Name: "FHLMC MBS", Weight: 3.42, Sector: "Government"},
		{Symbol: "USTIPS", Name: "US TIPS", Weight: 3.15, Sector: "Government"},
		{Symbol: "CORP1", Name: "Corporate Aaa/Aa", Weight: 2.88, Sector: "Corporate"},
		{Symbol: "CORP2", Name: "Corporate A/Baa", Weight: 2.62, Sector: "Corporate"},
		{Symbol: "UST1Y", Name: "US Treasury 1Y", Weight: 2.35, Sector: "Government"},
		{Symbol: "AGNC", Name: "Agency MBS", Weight: 2.08, Sector: "Government"},
		{Symbol: "CMBS", Name: "Commercial MBS", Weight: 1.85, Sector: "Securitized"},
		{Symbol: "ABS", Name: "Asset-Backed", Weight: 1.62, Sector: "Securitized"},
		{Symbol: "MUNI", Name: "Municipal Bonds", Weight: 1.38, Sector: "Municipal"},
		{Symbol: "INTL", Name: "Intl Bonds USD Hdg", Weight: 1.15, Sector: "International"},
		{Symbol: "EM", Name: "Emerging Markets", Weight: 0.92, Sector: "International"},
		{Symbol: "TIPS5", Name: "TIPS 5Y", Weight: 0.78, Sector: "Government"},
		{Symbol: "TIPS10", Name: "TIPS 10Y", Weight: 0.65, Sector: "Government"},
		{Symbol: "USTBILL", Name: "US T-Bills", Weight: 0.52, Sector: "Government"},
	},
}
