# Generated by Django 3.2.20 on 2025-12-26 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('data_update', '数据更新'), ('portfolio_analysis', '组合分析'), ('etf_comparison', 'ETF对比'), ('script_execute', '脚本执行'), ('scheduled_task', '定时任务'), ('manual_trigger', '手动触发'), ('page_view', '页面访问')], max_length=50, verbose_name='操作类型')),
                ('operation_name', models.CharField(max_length=200, verbose_name='操作名称')),
                ('operator', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作人')),
                ('status', models.IntegerField(choices=[(0, '进行中'), (1, '成功'), (2, '失败')], default=0, verbose_name='状态')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时(毫秒)')),
                ('input_params', models.JSONField(blank=True, null=True, verbose_name='输入参数')),
                ('output_result', models.JSONField(blank=True, null=True, verbose_name='输出结果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='用户代理')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='额外数据')),
                ('workflow_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='workflow.workflowinstance', verbose_name='工作流实例')),
            ],
            options={
                'verbose_name': '操作记录',
                'verbose_name_plural': '操作记录',
                'db_table': 'operation_log',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['operation_type', 'start_time'], name='operation_l_operati_f5e121_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['status', 'start_time'], name='operation_l_status_a245fb_idx'),
        ),
    ]
