# Generated by Django 3.2.20 on 2025-12-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20251226_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETFConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True, verbose_name='ETF代码')),
                ('name', models.CharField(max_length=200, verbose_name='ETF名称')),
                ('market', models.CharField(choices=[('US', '美股'), ('CN', 'A股')], default='US', max_length=10, verbose_name='市场')),
                ('strategy', models.CharField(blank=True, max_length=100, null=True, verbose_name='策略类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('focus', models.CharField(blank=True, max_length=50, null=True, verbose_name='焦点领域')),
                ('expense_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='费率(%)')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='状态')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'ETF配置',
                'verbose_name_plural': 'ETF配置',
                'db_table': 'etf_config',
                'ordering': ['market', 'sort_order', 'symbol'],
            },
        ),
    ]
