# Generated by Django 3.2.20 on 2025-12-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_etfconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etfconfig',
            name='market',
            field=models.CharField(choices=[('US', '美股'), ('CN', 'A股'), ('HK', '港股')], default='US', max_length=10, verbose_name='市场'),
        ),
    ]
