# Generated by Django 3.2.20 on 2025-12-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_add_hk_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('USD', '美元'), ('CNY', '人民币'), ('HKD', '港币')], max_length=10, verbose_name='源货币')),
                ('to_currency', models.CharField(choices=[('USD', '美元'), ('CNY', '人民币'), ('HKD', '港币')], max_length=10, verbose_name='目标货币')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='汇率')),
                ('rate_date', models.DateField(verbose_name='汇率日期')),
                ('data_source', models.CharField(blank=True, max_length=50, null=True, verbose_name='数据来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '汇率',
                'verbose_name_plural': '汇率',
                'db_table': 'exchange_rate',
                'ordering': ['-rate_date', 'from_currency', 'to_currency'],
            },
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['from_currency', 'to_currency'], name='exchange_ra_from_cu_26f89a_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['-rate_date'], name='exchange_ra_rate_da_ed0bb1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('from_currency', 'to_currency', 'rate_date')},
        ),
    ]
