// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"etf-insight/config"
	"etf-insight/router"
	"etf-insight/services"
	"etf-insight/services/datasource"
	"etf-insight/tasks"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeContainer 使用 Wire 自动注入所有依赖
// cfg 由 Bootstrap 阶段加载并传入
func InitializeContainer(cfg *config.Config) (*Container, error) {
	exchangeRateService := services.NewExchangeRateService()
	etfAnalysisService := services.NewETFAnalysisService(exchangeRateService)
	portfolioOptimizer := services.NewPortfolioOptimizer(etfAnalysisService)
	dataSourceProvider, err := ProvideDataSourceProvider()
	if err != nil {
		return nil, err
	}
	dataSourceConfig := ProvideExchangeRateConfig(cfg)
	exchangeRateTask := tasks.NewExchangeRateTask(dataSourceConfig)
	routerRouter := router.NewRouter(cfg, etfAnalysisService, portfolioOptimizer, dataSourceProvider, exchangeRateTask)
	scheduleConfig := ProvideScheduleConfig(cfg)
	scheduler := tasks.NewScheduler(scheduleConfig, etfAnalysisService, exchangeRateService, dataSourceProvider)
	container := &Container{
		Config:           cfg,
		Router:           routerRouter,
		Scheduler:        scheduler,
		ExchangeRateTask: exchangeRateTask,
		Provider:         dataSourceProvider,
		AnalysisService:  etfAnalysisService,
		Optimizer:        portfolioOptimizer,
		ExchangeService:  exchangeRateService,
	}
	return container, nil
}

// wire.go:

// ServiceSet 核心服务依赖集合
var ServiceSet = wire.NewSet(services.NewExchangeRateService, services.NewETFAnalysisService, services.NewPortfolioOptimizer, ProvideExchangeRateConfig,
	ProvideDataSourceProvider,
)

// TaskSet 定时任务依赖集合
var TaskSet = wire.NewSet(
	ProvideScheduleConfig, tasks.NewScheduler, tasks.NewExchangeRateTask,
)

// RouterSet 路由依赖集合
var RouterSet = wire.NewSet(router.NewRouter)

// Container 包含所有已构造的依赖项
type Container struct {
	Config           *config.Config
	Router           *router.Router
	Scheduler        *tasks.Scheduler
	ExchangeRateTask *tasks.ExchangeRateTask
	Provider         datasource.DataSourceProvider
	AnalysisService  *services.ETFAnalysisService
	Optimizer        *services.PortfolioOptimizer
	ExchangeService  *services.ExchangeRateService
}
